workspace:
  base: /go
  path: src/github.com/genofire/yaja

pipeline:
  build:
    image: golang:latest
    commands:
      - go get ./...
      - go build
  test:
    image: golang:latest
    commands:
      - go get github.com/stretchr/testify/assert
      - go test ./... -v -cover
