version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/dev.sum7.eu/genofire/yaja
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go install dev.sum7.eu/genofire/yaja
      - store_artifacts:
          path: /go/bin/
          destination: yaja
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/dev.sum7.eu/genofire/yaja
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go get github.com/mattn/goveralls
      - run: go get golang.org/x/tools/cmd/cover
      - run: ./.test-coverage circle-ci
      - store_test_results:
          path: ./
          destination: profile.cov
  test_race:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/dev.sum7.eu/genofire/yaja
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go test -race ./...
workflows:
  version: 2
  build_and_tests:
    jobs:
      - build
      - test
      - test_race
